"""Pydantic models for Storm-Vx profile validation.

Provides runtime validation and JSON schema generation for profile data.
SiteProfile remains the primary dataclass for backward compatibility;
these models are used for validation at serialization boundaries.

NOTE: This module intentionally does NOT use ``from __future__ import annotations``
because Pydantic V2 needs real runtime type objects for validation.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, ConfigDict, Field, field_validator
from urllib.parse import urlparse


class TechnologyEntry(BaseModel):
    """A detected technology with confidence score."""
    name: str
    confidence: float = Field(ge=0.0, le=1.0)
    category: str = ""


class FormEntry(BaseModel):
    """A detected HTML form."""
    action: str = ""
    method: str = "GET"
    fields: List[str] = Field(default_factory=list)


class WorkerConfig(BaseModel):
    """Worker scaling configuration."""
    initial_workers: int = Field(ge=1, default=5)
    max_workers: int = Field(ge=1, default=5000)
    step: int = Field(ge=1, default=50)
    step_duration: int = Field(ge=1, default=5)
    ramp_strategy: str = "GRADUAL"


class RequestConfig(BaseModel):
    """Request configuration."""
    timeout: int = Field(ge=1, default=10)
    follow_redirects: bool = True
    verify_ssl: bool = True
    keepalive: bool = True
    cache_bust: bool = True
    user_agent_rotation: bool = True
    delay_between_requests_ms: int = Field(ge=0, default=10)


class WAFStrategy(BaseModel):
    """WAF bypass strategy."""
    detected: bool = False
    waf_name: str = ""
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    bypass_methods: List[str] = Field(default_factory=list)


class AttackProfile(BaseModel):
    """Complete attack profile generated by the finder.

    Uses ``extra='ignore'`` so that fields generated by the engine
    (e.g. ``surgical_worker_config``, ``all_worker_config``) are
    silently ignored rather than raising ValidationError.
    """
    model_config = ConfigDict(extra='ignore')

    target_url: str = ""
    recommended_strategy: str = "GENERIC_FLOOD"
    strategy_reason: str = ""
    attack_vectors: List[str] = Field(default_factory=list)
    surgical_vectors: List[str] = Field(default_factory=list)
    all_vectors: List[str] = Field(default_factory=list)
    waf_strategy: WAFStrategy = Field(default_factory=WAFStrategy)
    worker_config: WorkerConfig = Field(default_factory=WorkerConfig)
    request_config: RequestConfig = Field(default_factory=RequestConfig)
    page_targets: List[str] = Field(default_factory=list)
    resource_targets: List[str] = Field(default_factory=list)
    evasion_config: Dict[str, Any] = Field(default_factory=dict)
    login_config: Dict[str, Any] = Field(default_factory=dict)
    timing_config: Dict[str, Any] = Field(default_factory=dict)
    asp_net_config: Dict[str, Any] = Field(default_factory=dict)
    php_config: Dict[str, Any] = Field(default_factory=dict)
    wordpress_config: Dict[str, Any] = Field(default_factory=dict)
    api_config: Dict[str, Any] = Field(default_factory=dict)
    spa_config: Dict[str, Any] = Field(default_factory=dict)
    edu_config: Dict[str, Any] = Field(default_factory=dict)
    risk_notes: List[str] = Field(default_factory=list)

    @field_validator('target_url')
    @classmethod
    def validate_url(cls, v: str) -> str:
        if v and not v.startswith(('http://', 'https://')):
            raise ValueError(f"target_url must start with http:// or https://, got: {v!r}")
        return v


class ProfileSchema(BaseModel):
    """Top-level profile schema for JSON validation."""
    url: str
    scheme: str = "https"
    domain: str = ""
    waf: Optional[str] = None
    cms: Optional[str] = None
    technologies: List[TechnologyEntry] = Field(default_factory=list)
    attack_profile: AttackProfile = Field(default_factory=AttackProfile)

    @field_validator('url')
    @classmethod
    def validate_url(cls, v: str) -> str:
        if not v:
            raise ValueError("url cannot be empty")
        parsed = urlparse(v)
        if parsed.scheme not in ('http', 'https'):
            raise ValueError(f"Invalid URL scheme: {parsed.scheme}")
        return v
